### ISSUE TITLE
Not compatible with aws-cdk v2

### ISSUE THREAD

**Issue by ignas-ideas** [pistazie/cdk-rest-api-integrations#90]
Hey, just wanted to mention that this package is not compatible with aws-cdk v2 anymore :)

**Comment by pistazie** [comment]
Hi. it used to be:) 
What error are you experiencing?

**Comment by pistazie** [comment]
that's right it isn't compatible.
Given the changes an improvements made in the CDK API around API Gateway integrations I think this repo isn't very relevant. I'll mark it deprecated.
